#!/usr/bin/env zsh
# Checks if there's a frame open

export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0

emacsclient -n -e "(if (> (length (frame-list)) 1) 't)" 2> /dev/null | grep t &> /dev/null

if [ "$?" -eq "1" ]; then
 emacsclient -a '' -nqc "$@" &> /dev/null
else
 emacsclient -nq "$@" &> /dev/null
fi
