- name: "tmux : install"
  tags:
    - tmux
  become: yes
  package:
    name:
      - tmux
    state: latest
  when: is_linux

- name: "tmux : install tpm"
  tags:
    - tmux
    - tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  when: is_linux

- name: "tmux : configuration"
  tags:
    - tmux
    - tmux-config
  file:
    src: ~/.dotfiles/tmux/files/tmux.conf
    dest: ~/.tmux.conf
    state: link
  when: is_linux

