# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $HOME/.zsh/0000_before.zsh
source $HOME/.zsh/0_path.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/history.zsh
source $HOME/.zsh/antigen.zsh
source $HOME/.zsh/asdf.zsh

[[ ! -f /home/duke/.acme.sh/acme.sh.env ]] || source /home/duke/.acme.sh/acme.sh.env
