- name: "yay : check pacman (arch)"
  tags:
    - yay
    - visual_code
    - languages
  shell: pacman -Q yay
  changed_when: false
  check_mode: false
  failed_when: false
  register: yay_install

- name: "yay : download package (arch)"
  tags:
    - yay
    - visual_code
    - languages
  get_url:
    url: https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
    dest: /tmp
  when:
    - is_arch
    - yay_install.stdout is defined and yay_install.stdout.find('yay') < 0

- name: "yay : unpack the package (arch)"
  tags:
    - yay
    - visual_code
    - languages
  unarchive:
    src: /tmp/yay.tar.gz
    dest: /tmp/
    copy: no
  when:
    - is_arch
    - yay_install.stdout is defined and yay_install.stdout.find('yay') < 0

- name: "yay : build and install (arch)"
  tags:
    - yay
    - visual_code
    - languages
  shell: cd /tmp/yay && makepkg -s -i --noconfirm
  when:
    - is_arch
    - yay_install.stdout is defined and yay_install.stdout.find('yay') < 0
