- name: "asdf : install asdf"
  tags:
    - asdf
    - languages
    - elixir
    - ruby
    - nodejs
    - golanf
    - erlang
    - rust
    - java
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/code/.asdf
    depth: 1
  when: is_linux or is_macos

- name: "asdf : fetch installed asdf plugins"
  tags:
    - asdf
    - languages
    - elixir
    - ruby
    - nodejs
    - golanf
    - erlang
    - rust
    - java
  shell: ~/code/.asdf/bin/asdf list
  register: asdf_list
  when: is_linux or is_macos

- name: "asdf : elixir"
  tags:
    - asdf
    - languages
    - elixir
  shell: ~/code/.asdf/bin/asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('elixir') == -1

- name: "asdf : ruby"
  tags:
    - asdf
    - languages
    - ruby
  shell: ~/code/.asdf/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('ruby') == -1

- name: "asdf : nodejs"
  tags:
    - asdf
    - languages
    - nodejs
  shell: ~/code/.asdf/bin/asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('nodejs') == -1

- name: "asdf : nodejs install lts"
  tags:
    - asdf
    - languages
    - nodejs
  shell: ~/code/.asdf/bin/asdf install nodejs latest
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('nodejs') != -1

- name: "asdf : erlang"
  tags:
    - asdf
    - languages
    - erlang
  shell: ~/code/.asdf/bin/asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('erlang') == -1

- name: "asdf : rust"
  tags:
    - asdf
    - languages
    - editor
    - vim
    - rust
  shell: ~/code/.asdf/bin/asdf plugin-add rust && /opt/asdf-vm/bin/asdf install rust stable && /opt/asdf-vm/bin/asdf global rust stable
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('rust') == -1

- name: "asdf : rust install stable"
  tags:
    - asdf
    - languages
    - rust
  shell: ~/code/.asdf/bin/asdf install rust stable
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('rust') != -1

- name: "asdf : golang"
  tags:
    - asdf
    - languages
    - golang
  shell: ~/code/.asdf/bin/asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('golang') == -1

- name: "asdf : java"
  tags:
    - asdf
    - languages
    - java
  shell: ~/code/.asdf/bin/asdf plugin-add java
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('java') == -1

- name: "asdf : maven"
  tags:
    - asdf
    - languages
    - java
  shell: ~/code/.asdf/bin/asdf plugin-add maven
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('java') == -1

- name: "asdf : nodejs npmrc"
  tags:
    - asdf
    - languages
    - nodejs
  file:
    src: "~/.dotfiles/asdf/files/npmrc"
    dest: "~/.npmrc"
    state: link
    force: yes
  when:
    - is_linux or is_macos
    - asdf_list.stdout is defined and asdf_list.stdout.find('nodejs') != -1

- name: "asdf : nodejs npmrc"
  tags:
    - asdf
    - languages
    - nodejs
  file:
    src: "~/.dotfiles/asdf/files/asdfrc"
    dest: "~/.asdfrc"
    state: link
    force: yes
  when:
    - is_linux or is_macos
