- name: "asdf : install asdf"
  tags:
    - asdf
    - languages
    - elixir
    - ruby
    - nodejs
    - golanf
    - erlang
    - rust
  yay:
    name:
      - asdf-vm 
    state: latest
    update_cache: yes
  when: is_linux

- name: "asdf : fetch installed asdf plugins"
  tags:
    - asdf
    - languages
    - elixir
    - ruby
    - nodejs
    - golanf
    - erlang
    - rust
  shell: /opt/asdf-vm/bin/asdf list
  register: asdf_list
  when: is_linux

- name: "asdf : elixir"
  tags:
    - asdf
    - languages
    - elixir
  shell: /opt/asdf-vm/bin/asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
  when:
    - is_linux
    - asdf_list.stdout is defined and asdf_list.stdout.find('elixir') == -1

- name: "asdf : ruby"
  tags:
    - asdf
    - languages
    - ruby
  shell: /opt/asdf-vm/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
  when:
    - is_linux
    - asdf_list.stdout is defined and asdf_list.stdout.find('ruby') == -1

- name: "asdf : nodejs"
  tags:
    - asdf
    - languages
    - nodejs
  shell: /opt/asdf-vm/bin/asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  when:
    - is_linux
    - asdf_list.stdout is defined and asdf_list.stdout.find('nodejs') == -1

- name: "asdf : nodejs install lts"
  tags:
    - asdf
    - languages
    - nodejs
  shell: /opt/asdf-vm/bin/asdf install nodejs lts 
  when:
    - is_linux
    - asdf_list.stdout is defined and asdf_list.stdout.find('nodejs') != -1

- name: "asdf : erlang"
  tags:
    - asdf
    - languages
    - erlang
  shell: /opt/asdf-vm/bin/asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
  when:
    - is_linux
    - asdf_list.stdout is defined and asdf_list.stdout.find('erlang') == -1

- name: "asdf : rust"
  tags:
    - asdf
    - languages
    - rust
  shell: /opt/asdf-vm/bin/asdf plugin-add rust && /opt/asdf-vm/bin/asdf install rust stable && /opt/asdf-vm/bin/asdf global rust stable
  when:
    - is_linux
    - asdf_list.stdout is defined and asdf_list.stdout.find('rust') == -1

- name: "asdf : golang"
  tags:
    - asdf
    - languages
    - golang
  shell: /opt/asdf-vm/bin/asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
  when:
    - is_linux
    - asdf_list.stdout is defined and asdf_list.stdout.find('golang') == -1

- name: "asdf : nodejs npmrc"
  tags:
    - asdf
    - languages
    - nodejs
  file:
    src: "~/.dotfiles/asdf/files/npmrc"
    dest: "~/.npmrc"
    state: link
    force: yes
  when:
    - is_linux
    - asdf_list.stdout is defined and asdf_list.stdout.find('nodejs') != -1